### ISSUE TITLE
I could not get the mouse cursor to read out in my environment.

### ISSUE THREAD

**Issue by ryusei-48** [hwf1324/mouseEnhancement#2]
I have been trying this add-on recently, but unfortunately the latest VS Code v1.94 is not able to read out the text under the mouse cursor.
I have not been able to read the mouse cursor since VS Code v1.91.1.
Then, I did not update VS Code, but I updated it to the latest version, hoping that it had recently improved, but the problem still occurred.
So if you have any suggestions for improvement, I would appreciate it if you could let me know and update this add-on if you know the cause.
Thank you.

issues: https://github.com/microsoft/vscode/issues/224704

## PS
I have just verified that the various drop-down items in the window menu are read, but not the tab label section of the open editor and the file tree in the left panel.

## environment
Windows 11 Pro
Visual Studio Code v1.94.2
NVDA v2024.3.1jp

**Comment by hwf1324** [comment]
Hi.

I'm sorry, unfortunately this solution requires the newly added API of NVDA2024.4 to work.

Thanks!

**Comment by ryusei-48** [comment]
Thanks for the reply.
I just found out about it today and installed the NVDA v2024.4-rc version to try it out.
I was able to track the mouse cursor in VS Code without any problems.
Thank you very much.
